// packages/solid/src/tanstack-ui/LinkButton.tsx

import { Link } from '@tanstack/solid-router'
import type { ComponentProps, JSX } from 'solid-js'
import { splitProps } from 'solid-js'
import { Button } from '../components/Button'

type LinkButtonProps = ComponentProps<typeof Button> & ComponentProps<typeof Link> & {
    children: JSX.Element
}

/**
 * LinkButton
 * - Wraps TanStack Solid Router's Link component with our Button styles
 * - Ensures consistent sizing/typography between links and buttons
 */
export function LinkButton(props: LinkButtonProps) {
    const [local, linkProps] = splitProps(props, ['variant', 'size', 'class', 'children'])
    return (
        <Link
            class={`gui-btn gui-btn--${local.variant || 'primary'} gui-btn--${local.size || 'md'} ${local.class || ''}`}
            {...linkProps}
        >
            {local.children}
        </Link>
    )
}

// src/react/tanstack-ui/LinkButton.tsx


import { Link } from '@tanstack/react-router'
import type { ComponentProps, ReactNode } from 'react'
import { Button } from '../components/Button'

type RouterLinkProps = ComponentProps<typeof Link>
type ButtonProps = ComponentProps<typeof Button>

type LinkButtonProps = Omit<ButtonProps, 'asChild' | 'type' | 'children'> &
  RouterLinkProps & {
    children: ReactNode
  }

/**
 * LinkButton
 * - Wraps TanStack Router's Link with our Button styles via `asChild`
 * - Ensures consistent sizing/typography between links and buttons
 */
export function LinkButton({
  variant = 'primary',
  size = 'md',
  className,
  children,
  ...linkProps
}: LinkButtonProps) {
  return (
    <Button asChild variant={variant} size={size} className={className}>
      <Link {...linkProps}>{children}</Link>
    </Button>
  )
}
