// packages/react/src/components/AnimateIn.tsx


import { ReactNode } from 'react'

interface AnimateInProps {
  children: ReactNode
  className?: string
  delay?: number
}

/**
 * Simple animation wrapper that fades in content
 * Used to provide smooth transitions when content loads
 */
export function AnimateIn({
  children,
  className = '',
  delay = 0,
}: AnimateInProps) {
  const style = delay > 0 ? { animationDelay: `${delay}ms` } : undefined

  return (
    <div
      className={`animate-in fade-in duration-200 ${className}`}
      style={style}
    >
      {children}
    </div>
  )
}

// packages/solid/src/components/AnimateIn.tsx


import { type ParentComponent, type JSX } from 'solid-js'
import { cn } from '../lib/utils'

interface AnimateInProps {
    children: JSX.Element
    class?: string
    delay?: number
}

/**
 * Simple animation wrapper that fades in content
 * Used to provide smooth transitions when content loads
 */
export const AnimateIn: ParentComponent<AnimateInProps> = (props) => {
    const style = () => props.delay && props.delay > 0 ? { 'animation-delay': `${props.delay}ms` } : undefined

    return (
        <div class={cn('animate-in fade-in duration-200', props.class)} style={style()}>
            {props.children}
        </div>
    )
}
